### ISSUE TITLE
SSL cert not trusted by Chrome 57+

### ISSUE THREAD

**Issue by gboudreau** [sqlitebrowser/DBHub.io-website#1]
Hi,

The website https://dbhub.io uses a SSL certificate generated by StartCom.
Starting with Google Chrome 57, the root CA for StartCom is not trusted anymore, which cause an error to be displayed to users visiting your website:

    There are issues with the site's certificate chain (net::ERR_CERT_AUTHORITY_INVALID).

I would suggest changing the SSL cert with something else. A Let's Encrypt certificate maybe?

Cheers.

Refs:
- [Distrusting WoSign and StartCom Certificates - Google Security Blog](https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html)
- [Restrict the set of WoSign/StartCom certs to the Alexa Top 1M - chromium/src - Git at Google](https://chromium.googlesource.com/chromium/src/+/e719fc626a3b9a528bf226b704785bcb24d07868)

**Comment by justinclift** [comment]
Thanks. :smile:

It's a known issue, though I hadn't bothered to create an issue for it.

Setting up LetsEncrypt instead is on my ToDo list, though I don't think it'll be done this week.

Reasonably likely next week though. :smile:

**Comment by justinclift** [comment]
@gboudreau Do you have time to try https://dbhub.io again?

I've just generated + installed a Lets Encrypt certificate for it manually.  It's only valid for 3 months (!), but we'll likely have the main server running at dbhub.io in the next few weeks anyway (using Lets Encrypt) instead of that 1 page website. :smile:

**Comment by gboudreau** [comment]
Working.

**Comment by justinclift** [comment]
Awesome @gboudreau, thanks for verifying. :smile:
